# Generated by Django 4.2.7 on 2025-11-01 09:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AttendanceSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('check_in_start', models.TimeField(default='09:00:00')),
                ('check_in_end', models.TimeField(default='10:00:00')),
                ('check_out_start', models.TimeField(default='17:00:00')),
                ('check_out_end', models.TimeField(default='18:00:00')),
                ('late_threshold', models.TimeField(default='09:15:00')),
                ('confidence_threshold', models.FloatField(default=0.6)),
                ('max_daily_hours', models.FloatField(default=8.0)),
            ],
        ),
        migrations.CreateModel(
            name='DailyReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(unique=True)),
                ('total_employees', models.IntegerField(default=0)),
                ('present_count', models.IntegerField(default=0)),
                ('absent_count', models.IntegerField(default=0)),
                ('late_count', models.IntegerField(default=0)),
                ('average_hours', models.FloatField(default=0.0)),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employee_id', models.CharField(max_length=20, unique=True)),
                ('department', models.CharField(max_length=100)),
                ('position', models.CharField(max_length=100)),
                ('phone_number', models.CharField(max_length=15)),
                ('face_encoding', models.TextField(blank=True, null=True)),
                ('face_image', models.ImageField(blank=True, null=True, upload_to='faces/')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attendance_type', models.CharField(choices=[('check_in', 'Check In'), ('check_out', 'Check Out')], max_length=10)),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now)),
                ('location', models.CharField(blank=True, max_length=100, null=True)),
                ('confidence_score', models.FloatField(blank=True, null=True)),
                ('image_capture', models.ImageField(blank=True, null=True, upload_to='attendance_captures/')),
                ('notes', models.TextField(blank=True, null=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.employee')),
            ],
            options={
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['employee', 'timestamp'], name='core_attend_employe_19445d_idx')],
            },
        ),
    ]
