# Generated by Django 4.2.7 on 2025-11-02 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendancesettings',
            name='min_hours_before_checkout',
            field=models.FloatField(default=3.0, help_text='Minimum hours required between check-in and check-out'),
        ),
    ]
