# Generated by Django 4.2.7 on 2025-11-09 15:27

from decimal import Decimal
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_holiday_joiningdetail_leaveapplication_leavetype_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('working_days', models.CharField(choices=[('5_day', 'Mon–Fri'), ('6_day', 'Mon–Sat'), ('custom', 'Custom (use flags below)')], default='5_day', max_length=10)),
                ('saturday_is_working', models.BooleanField(default=False)),
                ('sunday_is_working', models.BooleanField(default=False)),
                ('full_day_hours', models.FloatField(default=8.0)),
                ('half_day_hours', models.FloatField(default=4.0)),
                ('overtime_rate', models.DecimalField(decimal_places=2, default=Decimal('100.00'), max_digits=10)),
                ('count_weekend_overtime', models.BooleanField(default=True)),
                ('count_holiday_overtime', models.BooleanField(default=True)),
            ],
        ),
        migrations.AddField(
            model_name='leavetype',
            name='is_paid',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='payroll',
            name='absent_days',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=6),
        ),
        migrations.AddField(
            model_name='payroll',
            name='half_days',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=6),
        ),
        migrations.AddField(
            model_name='payroll',
            name='overtime_hours',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=7),
        ),
        migrations.AddField(
            model_name='payroll',
            name='paid_leave_days',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=6),
        ),
        migrations.AddField(
            model_name='payroll',
            name='present_days',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=6),
        ),
        migrations.AddField(
            model_name='payroll',
            name='remarks',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='payroll',
            name='unpaid_leave_days',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=6),
        ),
        migrations.AddField(
            model_name='payrollsettings',
            name='default_count_holiday_overtime',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='payrollsettings',
            name='default_count_weekend_overtime',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='payrollsettings',
            name='default_full_day_hours',
            field=models.FloatField(default=8.0),
        ),
        migrations.AddField(
            model_name='payrollsettings',
            name='default_half_day_hours',
            field=models.FloatField(default=4.0),
        ),
        migrations.AddField(
            model_name='payrollsettings',
            name='default_overtime_rate',
            field=models.DecimalField(decimal_places=2, default=Decimal('100.00'), max_digits=10),
        ),
        migrations.AddField(
            model_name='payrollsettings',
            name='default_saturday_is_working',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='payrollsettings',
            name='default_sunday_is_working',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='payrollsettings',
            name='default_working_days',
            field=models.CharField(choices=[('5_day', 'Mon–Fri'), ('6_day', 'Mon–Sat')], default='5_day', max_length=10),
        ),
        migrations.AddField(
            model_name='employee',
            name='work_rule',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='employees', to='core.workrule'),
        ),
    ]
