# Generated by Django 4.2.7 on 2026-01-05 06:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_workrule_leavetype_is_paid_payroll_absent_days_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='payroll',
            name='payslip_pdf',
            field=models.FileField(blank=True, null=True, upload_to='payslips/'),
        ),
        migrations.AddField(
            model_name='salarystructure',
            name='hourly_override',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Optional custom hourly rate', max_digits=10, null=True),
        ),
    ]
