# Generated by Django 4.2.7 on 2026-01-05 07:01

import datetime
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_payroll_payslip_pdf_salarystructure_hourly_override'),
    ]

    operations = [
        migrations.AddField(
            model_name='workrule',
            name='night_bonus_multiplier',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.20'), max_digits=5),
        ),
        migrations.AddField(
            model_name='workrule',
            name='night_shift_end',
            field=models.TimeField(default=datetime.time(6, 0)),
        ),
        migrations.AddField(
            model_name='workrule',
            name='night_shift_start',
            field=models.TimeField(default=datetime.time(22, 0)),
        ),
        migrations.AddField(
            model_name='workrule',
            name='shift_end_time',
            field=models.TimeField(default=datetime.time(18, 0)),
        ),
        migrations.AddField(
            model_name='workrule',
            name='shift_start_time',
            field=models.TimeField(default=datetime.time(9, 0)),
        ),
        migrations.AlterField(
            model_name='workrule',
            name='working_days',
            field=models.CharField(choices=[('5_day', 'Mon–Fri'), ('6_day', 'Mon–Sat'), ('custom', 'Custom')], default='5_day', max_length=10),
        ),
    ]
