# Generated by Django 4.2.7 on 2026-01-05 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_workrule_night_bonus_multiplier_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='payroll',
            name='actual_paid_salary',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Actual salary paid after manual override (if any)', max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='payroll',
            name='calculated_salary',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='System calculated salary before override', max_digits=10, null=True),
        ),
    ]
