# Generated by Django 4.2.7 on 2026-02-13 14:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_payroll_actual_paid_salary_payroll_calculated_salary'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payroll',
            name='actual_paid_salary',
        ),
        migrations.RemoveField(
            model_name='payroll',
            name='next_pay_date',
        ),
        migrations.RemoveField(
            model_name='payroll',
            name='paid_leave_days',
        ),
        migrations.RemoveField(
            model_name='payroll',
            name='payslip_pdf',
        ),
        migrations.RemoveField(
            model_name='payroll',
            name='remarks',
        ),
        migrations.RemoveField(
            model_name='payroll',
            name='unpaid_leave_days',
        ),
        migrations.RemoveField(
            model_name='salarystructure',
            name='hourly_override',
        ),
        migrations.RemoveField(
            model_name='workrule',
            name='night_bonus_multiplier',
        ),
        migrations.RemoveField(
            model_name='workrule',
            name='night_shift_end',
        ),
        migrations.RemoveField(
            model_name='workrule',
            name='night_shift_start',
        ),
        migrations.AlterField(
            model_name='payroll',
            name='calculated_salary',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='payroll',
            name='month',
            field=models.DateField(help_text='First day of month'),
        ),
        migrations.AlterField(
            model_name='salarystructure',
            name='employee',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='salary_structure', to='core.employee'),
        ),
        migrations.AlterField(
            model_name='workrule',
            name='shift_end_time',
            field=models.TimeField(default='18:00'),
        ),
        migrations.AlterField(
            model_name='workrule',
            name='shift_start_time',
            field=models.TimeField(default='09:00'),
        ),
    ]
