# Generated by Django 4.2.7 on 2026-02-13 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_remove_payroll_actual_paid_salary_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payroll',
            name='calculated_salary',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='payroll',
            name='net_salary',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
