# Generated by Django 4.2.7 on 2026-02-14 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_alter_payroll_calculated_salary_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='payroll',
            name='payslip_pdf',
            field=models.FileField(blank=True, null=True, upload_to='payslips/'),
        ),
    ]
