# Generated by Django 4.2.7 on 2026-02-17 02:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_payroll_payslip_pdf'),
    ]

    operations = [
        migrations.CreateModel(
            name='AttendanceMatchLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employee_id', models.CharField(max_length=20)),
                ('cosine', models.FloatField()),
                ('euclidean', models.FloatField()),
                ('confidence', models.CharField(max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='FaceMatchStats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employee_id', models.CharField(max_length=20, unique=True)),
                ('false_rejects', models.IntegerField(default=0)),
                ('false_accepts', models.IntegerField(default=0)),
                ('total_attempts', models.IntegerField(default=0)),
            ],
        ),
    ]
