# Generated by Django 4.2.7 on 2026-02-17 02:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_attendancematchlog_facematchstats'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmployeeThreshold',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employee_id', models.CharField(max_length=20, unique=True)),
                ('cos_max', models.FloatField(default=0.85)),
                ('euc_max', models.FloatField(default=1.4)),
            ],
        ),
    ]
