# Generated by Django 4.2.7 on 2026-02-18 12:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_employeethreshold'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='joiningdetail',
            name='documents',
        ),
        migrations.AlterField(
            model_name='department',
            name='name',
            field=models.CharField(choices=[('Management', 'Management / CEO Office'), ('HR', 'Human Resources'), ('Finance', 'Finance / Accounts'), ('IT', 'IT / Technical'), ('Operations', 'Operations'), ('Pharmacy', 'Pharmacy'), ('House Keeping', 'House Keeping'), ('Nursing', 'Nursing'), ('Reception', 'Reception'), ('Sales', 'Sales & Marketing'), ('Other', 'Other')], max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='joiningdetail',
            name='employee',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='joining_detail', to='core.employee'),
        ),
        migrations.AlterField(
            model_name='joiningdocument',
            name='joining',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='core.joiningdetail'),
        ),
    ]
