# Generated by Django 4.2.7 on 2026-02-18 13:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_remove_joiningdetail_documents_alter_department_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='joiningdetail',
            name='documents',
            field=models.FileField(blank=True, null=True, upload_to='joining_documents/'),
        ),
        migrations.AlterField(
            model_name='joiningdetail',
            name='employee',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='core.employee'),
        ),
        migrations.AlterField(
            model_name='joiningdocument',
            name='joining',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='joining_documents', to='core.joiningdetail'),
        ),
    ]
