# Generated by Django 4.2.7 on 2026-02-18 14:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_joiningdetail_documents_alter_joiningdetail_employee_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='joiningdetail',
            name='documents',
        ),
    ]
