# Generated by Django 4.2.7 on 2026-02-20 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_officelocation_employee_location_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='officelocation',
            name='location_type',
            field=models.CharField(choices=[('INDOOR', 'Indoor'), ('OUTDOOR', 'Outdoor')], default='INDOOR', max_length=10),
        ),
    ]
