# Generated by Django 4.2.7 on 2026-02-20 15:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_officelocation_location_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='officelocation',
            name='location_type',
        ),
    ]
