# Generated by Django 4.2.7 on 2026-02-22 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_remove_officelocation_location_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='payroll',
            name='hourly_rate',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='payroll',
            name='total_work_hours',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=7),
        ),
    ]
