# Generated by Django 4.2.7 on 2026-02-22 13:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_payroll_hourly_rate_payroll_total_work_hours'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payroll',
            name='hourly_rate',
        ),
        migrations.RemoveField(
            model_name='payroll',
            name='total_work_hours',
        ),
    ]
