# Generated by Django 4.2.7 on 2026-02-26 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0020_remove_payroll_hourly_rate_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='workrule',
            name='flexible_attendance',
            field=models.BooleanField(default=False, help_text='Allow check-in/check-out at any time (for gardener/cleaning staff)'),
        ),
    ]
