# Generated by Django 4.2.7 on 2026-03-08 13:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0021_workrule_flexible_attendance'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmployeeShiftAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField()),
                ('end_date', models.DateField(blank=True, null=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.employee')),
                ('work_rule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.workrule')),
            ],
        ),
    ]
