# Generated by Django 4.2.7 on 2026-03-08 14:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0022_employeeshiftassignment'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='employeeshiftassignment',
            options={'ordering': ['-start_date']},
        ),
        migrations.AlterField(
            model_name='employeeshiftassignment',
            name='employee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shift_assignments', to='core.employee'),
        ),
        migrations.AddIndex(
            model_name='employeeshiftassignment',
            index=models.Index(fields=['employee', 'start_date', 'end_date'], name='core_employ_employe_19268e_idx'),
        ),
    ]
