# Generated by Django 4.2.7 on 2026-03-08 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0023_alter_employeeshiftassignment_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='payroll',
            name='holiday_overtime_hours',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Weekend/Holiday Extra Hours', max_digits=7),
        ),
        migrations.AddField(
            model_name='payroll',
            name='late_days_count',
            field=models.PositiveIntegerField(default=0, help_text='Total days employee arrived late'),
        ),
        migrations.AddField(
            model_name='payroll',
            name='late_penalty_deduction',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Days deducted as late penalty', max_digits=6),
        ),
        migrations.AddField(
            model_name='payroll',
            name='paid_leave_days_count',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=6),
        ),
        migrations.AlterField(
            model_name='payroll',
            name='basic_pay',
            field=models.DecimalField(decimal_places=2, help_text='Earned Basic (After pro-rata/LOP)', max_digits=10),
        ),
        migrations.AlterField(
            model_name='payroll',
            name='overtime_hours',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Regular Overtime', max_digits=7),
        ),
        migrations.AlterUniqueTogether(
            name='payroll',
            unique_together={('employee', 'month')},
        ),
        migrations.AddIndex(
            model_name='payroll',
            index=models.Index(fields=['month', 'status'], name='core_payrol_month_e401ad_idx'),
        ),
    ]
