# Generated by Django 4.2.7 on 2026-03-29 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0024_payroll_holiday_overtime_hours_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='workrule',
            name='max_overtime_hours',
            field=models.DecimalField(decimal_places=2, default=4, help_text='Max overtime allowed before counting extra shift', max_digits=5),
        ),
    ]
