# Generated by Django 4.2.7 on 2026-04-05 04:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0025_workrule_max_overtime_hours'),
    ]

    operations = [
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True)),
                ('slug', models.SlugField(unique=True)),
                ('description', models.TextField(blank=True)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('address', models.TextField(blank=True)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='org_logos/')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.AlterModelOptions(
            name='holiday',
            options={'ordering': ['date']},
        ),
        migrations.AlterField(
            model_name='dailyreport',
            name='date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='department',
            name='name',
            field=models.CharField(choices=[('Management', 'Management / CEO Office'), ('HR', 'Human Resources'), ('Finance', 'Finance / Accounts'), ('IT', 'IT / Technical'), ('Operations', 'Operations'), ('Pharmacy', 'Pharmacy'), ('House Keeping', 'House Keeping'), ('Nursing', 'Nursing'), ('Reception', 'Reception'), ('Sales', 'Sales & Marketing'), ('Other', 'Other')], max_length=100),
        ),
        migrations.AlterField(
            model_name='employee',
            name='employee_id',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='employeethreshold',
            name='employee_id',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='facematchstats',
            name='employee_id',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='holiday',
            name='date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='leaveworkflowstage',
            name='level',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='workrule',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AddField(
            model_name='organization',
            name='admin_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='admin_organizations', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='attendance',
            name='organization',
            field=models.ForeignKey(null=True, blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='attendances', to='core.organization'),
        ),
        migrations.AddField(
            model_name='attendancematchlog',
            name='organization',
            field=models.ForeignKey(null=True, blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='match_logs', to='core.organization'),
        ),
        migrations.AddIndex(
            model_name='attendancematchlog',
            index=models.Index(fields=['organization', 'employee_id', 'created_at'], name='core_attend_organiz_8545f3_idx'),
        ),
        migrations.AddField(
            model_name='attendancesettings',
            name='organization',
            field=models.OneToOneField(null=True, blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='attendance_settings', to='core.organization'),
        ),
        migrations.AddField(
            model_name='dailyreport',
            name='organization',
            field=models.ForeignKey(null=True, blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='daily_reports', to='core.organization'),
        ),
        migrations.AddField(
            model_name='department',
            name='organization',
            field=models.ForeignKey(null=True, blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='departments', to='core.organization'),
        ),
        migrations.AddField(
            model_name='employee',
            name='organization',
            field=models.ForeignKey(null=True, blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='employees', to='core.organization'),
        ),
        migrations.AddField(
            model_name='employeethreshold',
            name='organization',
            field=models.ForeignKey(null=True, blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='employee_thresholds', to='core.organization'),
        ),
        migrations.AddField(
            model_name='facematchstats',
            name='organization',
            field=models.ForeignKey(null=True, blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='face_stats', to='core.organization'),
        ),
        migrations.AddField(
            model_name='holiday',
            name='organization',
            field=models.ForeignKey(null=True, blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='holidays', to='core.organization'),
        ),
        migrations.AddField(
            model_name='leavetype',
            name='organization',
            field=models.ForeignKey(null=True, blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='leave_types', to='core.organization'),
        ),
        migrations.AddField(
            model_name='leaveworkflowstage',
            name='organization',
            field=models.ForeignKey(null=True, blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='leave_workflow_stages', to='core.organization'),
        ),
        migrations.AddField(
            model_name='officelocation',
            name='organization',
            field=models.ForeignKey(null=True, blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='office_locations', to='core.organization'),
        ),
        migrations.AddField(
            model_name='workrule',
            name='organization',
            field=models.ForeignKey(null=True, blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='work_rules', to='core.organization'),
        ),
        migrations.AlterUniqueTogether(
            name='dailyreport',
            unique_together={('organization', 'date')},
        ),
        migrations.AlterUniqueTogether(
            name='department',
            unique_together={('organization', 'name')},
        ),
        migrations.AlterUniqueTogether(
            name='employee',
            unique_together={('organization', 'employee_id')},
        ),
        migrations.AlterUniqueTogether(
            name='employeethreshold',
            unique_together={('organization', 'employee_id')},
        ),
        migrations.AlterUniqueTogether(
            name='facematchstats',
            unique_together={('organization', 'employee_id')},
        ),
        migrations.AlterUniqueTogether(
            name='holiday',
            unique_together={('organization', 'date')},
        ),
        migrations.AlterUniqueTogether(
            name='leavetype',
            unique_together={('organization', 'name')},
        ),
        migrations.AlterUniqueTogether(
            name='leaveworkflowstage',
            unique_together={('organization', 'level')},
        ),
        migrations.AlterUniqueTogether(
            name='officelocation',
            unique_together={('organization', 'name')},
        ),
        migrations.AlterUniqueTogether(
            name='workrule',
            unique_together={('organization', 'name')},
        ),
    ]
