# Generated by Django 4.2.7 on 2026-04-05 05:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0027_alter_attendance_organization_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendance',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendances', to='core.organization'),
        ),
        migrations.AlterField(
            model_name='attendancematchlog',
            name='organization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='match_logs', to='core.organization'),
        ),
        migrations.AlterField(
            model_name='attendancesettings',
            name='organization',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='attendance_settings', to='core.organization'),
        ),
        migrations.AlterField(
            model_name='dailyreport',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_reports', to='core.organization'),
        ),
        migrations.AlterField(
            model_name='department',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='departments', to='core.organization'),
        ),
        migrations.AlterField(
            model_name='employeethreshold',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='employee_thresholds', to='core.organization'),
        ),
        migrations.AlterField(
            model_name='facematchstats',
            name='organization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='face_stats', to='core.organization'),
        ),
        migrations.AlterField(
            model_name='holiday',
            name='organization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='holidays', to='core.organization'),
        ),
        migrations.AlterField(
            model_name='leavetype',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='leave_types', to='core.organization'),
        ),
        migrations.AlterField(
            model_name='leaveworkflowstage',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='leave_workflow_stages', to='core.organization'),
        ),
        migrations.AlterField(
            model_name='officelocation',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='office_locations', to='core.organization'),
        ),
        migrations.AlterField(
            model_name='workrule',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='work_rules', to='core.organization'),
        ),
    ]
