# Generated by Django 4.2.7 on 2026-04-05 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0028_alter_attendance_organization_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='organization',
            name='admin_user',
        ),
        migrations.AlterModelOptions(
            name='holiday',
            options={},
        ),
        migrations.RemoveIndex(
            model_name='attendancematchlog',
            name='core_attend_organiz_8545f3_idx',
        ),
        migrations.AlterUniqueTogether(
            name='dailyreport',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='department',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='employee',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='employeethreshold',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='facematchstats',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='holiday',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='leavetype',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='leaveworkflowstage',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='officelocation',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='workrule',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='attendance',
            name='organization',
        ),
        migrations.RemoveField(
            model_name='attendancematchlog',
            name='organization',
        ),
        migrations.RemoveField(
            model_name='attendancesettings',
            name='organization',
        ),
        migrations.AlterField(
            model_name='dailyreport',
            name='date',
            field=models.DateField(unique=True),
        ),
        migrations.AlterField(
            model_name='department',
            name='name',
            field=models.CharField(choices=[('Management', 'Management / CEO Office'), ('HR', 'Human Resources'), ('Finance', 'Finance / Accounts'), ('IT', 'IT / Technical'), ('Operations', 'Operations'), ('Pharmacy', 'Pharmacy'), ('House Keeping', 'House Keeping'), ('Nursing', 'Nursing'), ('Reception', 'Reception'), ('Sales', 'Sales & Marketing'), ('Other', 'Other')], max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='employee',
            name='employee_id',
            field=models.CharField(max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name='employeethreshold',
            name='employee_id',
            field=models.CharField(max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name='facematchstats',
            name='employee_id',
            field=models.CharField(max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name='holiday',
            name='date',
            field=models.DateField(unique=True),
        ),
        migrations.AlterField(
            model_name='leaveworkflowstage',
            name='level',
            field=models.PositiveIntegerField(unique=True),
        ),
        migrations.AlterField(
            model_name='workrule',
            name='name',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.RemoveField(
            model_name='dailyreport',
            name='organization',
        ),
        migrations.RemoveField(
            model_name='department',
            name='organization',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='organization',
        ),
        migrations.RemoveField(
            model_name='employeethreshold',
            name='organization',
        ),
        migrations.RemoveField(
            model_name='facematchstats',
            name='organization',
        ),
        migrations.RemoveField(
            model_name='holiday',
            name='organization',
        ),
        migrations.RemoveField(
            model_name='leavetype',
            name='organization',
        ),
        migrations.RemoveField(
            model_name='leaveworkflowstage',
            name='organization',
        ),
        migrations.RemoveField(
            model_name='officelocation',
            name='organization',
        ),
        migrations.RemoveField(
            model_name='workrule',
            name='organization',
        ),
        migrations.DeleteModel(
            name='Organization',
        ),
    ]
