# Generated by Django 5.2.15 on 2026-06-17 04:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0029_remove_organization_admin_user_alter_holiday_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='department',
            name='name',
            field=models.CharField(choices=[('Management', 'Management / CEO Office'), ('HR', 'Human Resources'), ('Finance', 'Finance / Accounts'), ('IT', 'IT / Technical'), ('Operations', 'Operations'), ('Doctor', 'Doctor'), ('Nursing', 'Nursing'), ('OPD', 'Out Patient Department (OPD)'), ('IPD', 'In Patient Department (IPD)'), ('Laboratory', 'Laboratory / Pathology'), ('Pharmacy', 'Pharmacy'), ('ICU', 'ICU / Critical Care'), ('OT', 'Operation Theatre'), ('Radiology', 'Radiology / Imaging'), ('Security', 'Security'), ('Maintenance', 'Maintenance & Engineering'), ('Ambulance', 'Ambulance Services'), ('Emergency', 'Emergency / Casualty'), ('Reception', 'Reception / Front Desk'), ('Medical Records', 'Medical Records Department'), ('Store', 'Store & Inventory'), ('House Keeping', 'House Keeping'), ('Sales', 'Sales & Marketing'), ('Other', 'Other')], max_length=100, unique=True),
        ),
    ]
