# Generated by Django 5.2.15 on 2026-06-21 06:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0031_organisation_attendance_organisation_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dailyreport',
            name='date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='department',
            name='name',
            field=models.CharField(choices=[('Management', 'Management / CEO Office'), ('HR', 'Human Resources'), ('Finance', 'Finance / Accounts'), ('IT', 'IT / Technical'), ('Operations', 'Operations'), ('Doctor', 'Doctor'), ('Nursing', 'Nursing'), ('OPD', 'Out Patient Department (OPD)'), ('IPD', 'In Patient Department (IPD)'), ('Laboratory', 'Laboratory / Pathology'), ('Pharmacy', 'Pharmacy'), ('ICU', 'ICU / Critical Care'), ('OT', 'Operation Theatre'), ('Radiology', 'Radiology / Imaging'), ('Security', 'Security'), ('Maintenance', 'Maintenance & Engineering'), ('Ambulance', 'Ambulance Services'), ('Emergency', 'Emergency / Casualty'), ('Reception', 'Reception / Front Desk'), ('Medical Records', 'Medical Records Department'), ('Store', 'Store & Inventory'), ('House Keeping', 'House Keeping'), ('Sales', 'Sales & Marketing'), ('Other', 'Other')], max_length=100),
        ),
        migrations.AlterField(
            model_name='employee',
            name='employee_id',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='employeethreshold',
            name='employee_id',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='facematchstats',
            name='employee_id',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='holiday',
            name='date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='leaveworkflowstage',
            name='level',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='workrule',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterUniqueTogether(
            name='dailyreport',
            unique_together={('organisation', 'date')},
        ),
        migrations.AlterUniqueTogether(
            name='department',
            unique_together={('organisation', 'name')},
        ),
        migrations.AlterUniqueTogether(
            name='employee',
            unique_together={('organisation', 'employee_id')},
        ),
        migrations.AlterUniqueTogether(
            name='employeethreshold',
            unique_together={('organisation', 'employee_id')},
        ),
        migrations.AlterUniqueTogether(
            name='facematchstats',
            unique_together={('organisation', 'employee_id')},
        ),
        migrations.AlterUniqueTogether(
            name='holiday',
            unique_together={('organisation', 'date')},
        ),
        migrations.AlterUniqueTogether(
            name='leaveworkflowstage',
            unique_together={('organisation', 'level')},
        ),
        migrations.AlterUniqueTogether(
            name='workrule',
            unique_together={('organisation', 'name')},
        ),
    ]
